# Use an official Python base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the Python script to the container
COPY app.py .

# Run the Python script
CMD ["python", "db.py"]
