name: Build and Push Multi-Module Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [API-dotnet, Log-Manager, Web-App-Angular, Mobile-Application, db]  # Add all modules here

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check if Changes Exist in Module
        id: check_changes
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "^${{ matrix.module }}/"; then
            echo "CHANGED=true" >> $GITHUB_ENV
          else
            echo "CHANGED=false" >> $GITHUB_ENV
          fi

      - name: Stop if No Changes
        if: env.CHANGED == 'false'
        run: echo "No changes in ${{ matrix.module }}, skipping..." && exit 0
        
      - name: Extract Branch Name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Convert Module Name to Lowercase
        run: echo "MODULE_LOWER=$(echo '${{ matrix.module }}' | tr '[:upper:]' '[:lower:]' | tr -d ' ')" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t uamng/${{ env.MODULE_LOWER }}:${{ env.BRANCH_NAME }} ./${{ matrix.module }}

      - name: Push Docker Image
        run: |
          docker push uamng/${{ env.MODULE_LOWER }}:${{ env.BRANCH_NAME }}
