name: Build and Push Multi-Module Docker Images

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [API-dotnet, Log-Manager]  # List of modules

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Branch Name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t uamng/api-dotnet:${{ env.BRANCH_NAME }} ./${{ matrix.module }}

      - name: Push Docker Image
        run: |
          docker push uamng/api-dotnet:${{ env.BRANCH_NAME }}


